# Device: Astra
# Note to self:
# - Relay1 styr huvudström
# - Relay2 styr pump
# - Relay3 styr värmare
# - Relay4 oanvänd

substitutions:
  network: "192.168.12"
  device_num: "100"
  device_type: "astra-br4g8al"
  device_subtype: ""
  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  # admin_password: !secret otaPWD
  # new_ota_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "4ch relä, r1 = huvudström, r2 = pump, r3 = värmare"
  em_route: ""

# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
esphome:
  name: ${device_name}
  # on_boot:
  #   - lambda: |-
  #       id(overtheair).set_auth_password(to_string("${new_ota_password}"));
  # # buzzer on on startup
  #   priority: -100
  #   then:
  #     #- rtttl.play: 'Indiana:d=4,o=5,b=250:e,8p,8f,8g,8p,1c6,8p.,d,8p,8e,1f,p.,g,8p,8a,8b,8p,1f6,p,a,8p,8b,2c6,2d6,2e6,e,8p,8f,8g,8p,1c6,p,d6,8p,8e6,1f.6,g,8p,8g,e.6,8p,d6,8p,8g,e.6,8p,d6,8p,8g,f.6,8p,e6,8p,8d6,2c6'
  #     - rtttl.play: 'RGB:d=4,o=5,b=240:8a.,32p,8a.,32p,8a#,4c6,8a#,8a.,32p,8a.,32p,8a#,4c6,8a#,8a.,16p,8c6.,8p,8d6.,8p,8f6.,8p,4g6,4p.,4c6.'

# wifi:
#  use_address: 192.168.12.200

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: WARN

output:
  - platform: gpio
    pin: GPIO25
    id: "output_1"
  - platform: gpio
    pin: GPIO26
    id: "output_2"
  - platform: gpio
    pin: GPIO33
    id: "output_3"
  - platform: gpio
    pin: GPIO32
    id: "output_4"
  
switch:
  - platform: output
    name: "Switch 1"
    id: "switch_1"
    output: "output_1"
    restore_mode: ALWAYS_ON
  - platform: output
    name: "Switch 2"
    id: "switch_2"
    output: "output_2"
    restore_mode: ALWAYS_OFF
  - platform: output
    name: "Switch 3"
    id: "switch_3"
    output: "output_3"
    restore_mode: ALWAYS_OFF
  - platform: output
    name: "Switch 4"
    id: "switch_4"
    output: "output_4"

sensor:
  - platform: adc
    name: Fuel Level
    pin: GPIO39
    accuracy_decimals: 2
    update_interval: 10s
    attenuation: 0dB
#    filters:
#      - multiply: 2.0 


# binary_sensor:
  # - platform: gpio
  #   pin:
  #     number: GPIO0
  #     mode: INPUT_PULLUP
  #     inverted: True
  #   name: "Button 1"
  #   on_press:
  #     - logger.log: "$device_name Button 1"
  #     - switch.toggle: switch_1
  # - platform: gpio
  #   pin:
  #     number: GPIO09
  #     mode: INPUT_PULLUP
  #     inverted: True
  #   name: "Button 2"
  #   on_press:
  #     - logger.log: "$device_name Button 2"
  #     - switch.toggle: switch_2
  # - platform: gpio
  #   pin:
  #     number: GPIO10
  #     mode: INPUT_PULLUP
  #     inverted: True
  #   name: "Button 3"
  #   on_press:
  #     - logger.log: "$device_name Button 3"
  #     - switch.toggle: switch_3
  # - platform: gpio
  #   pin:
  #     number: GPIO14
  #     mode: INPUT_PULLUP
  #     inverted: True
  #   name: "Button 4"
  #   on_press:
  #     - logger.log: "$device_name Button 4"
  #     - switch.toggle: switch_4

# output:
#   - platform: ledc
#     pin: GPIO12
#     id: rtttl_out

# rtttl:
#   output: rtttl_out
 


packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
    refresh: 300s

