# Set variables such as the device's name and friendly name
# The devicename is used internally which the friendly name is shown in the user interface
# Device: Shelly Plus 1PM 
substitutions:
  network: "192.168.12"
  device_num: "65"
  device_type: "shelly-plus1pm"

  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  #admin_password: !secret otaPWD
  #new_ota_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_update_interval: 5s
  em_usage: "Bastukammaren, mäter elförbruking i värmebatteri, L2"
  em_route: "gl|2-fm|2-d"

# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
#esphome:
#  on_boot:
#    - lambda: |-
#        id(overtheair).set_auth_password(to_string("${new_ota_password}"));

# Enable logging
logger:
  level: WARN

binary_sensor:
  - id: !extend switch_sensor
    # override default toggling when switched, now SWITCH_ON = RELAY_ON IF OFF, SWITCH_OFF = RELAY_OFF IF ON
    on_state: 
      then: 
        - lambda: |-
            if (id(switch_sensor).state) {
              // Binary sensor is ON, do something here
              id(relay).turn_on();
            } else {
              // Binary sensor is OFF, do something else here
              id(relay).turn_off();
            }

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - devices/ep_esphome_device_shelly_plus1pm.yaml # Device-specific defaults
    refresh: 300s
