# Set variables such as the device's name and friendly name
# The devicename is used internally which the friendly name is shown in the user interface
# Device: Shelly Plus 1PM 
substitutions:
  network: "192.168.12"
  device_num: "66"
  device_type: "shelly-plus1pm"
  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}" # 192.168.12.66
  wifi_ssid: "ajOuTiWiFi"
  wifi_pwd: !secret wifiPWD
  mqtt_user: "fi643007483316970021"
  mqtt_pwd: !secret wifiPWD
  admin_pwd: !secret wifiPWD
  #admin_pwd: !secret otaPWD
  #new_ota_pwd: !secret wifiPWD
  ca_certificates: !secret letsencrypt_cacerts
  em_usage: "WiGa vägguttag bakom vitrinskåp"
  em_route: "n|0-f001|25-e001|40ma-f002|c16-t"
  em_update_interval: 5s


# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
#esphome:
# on_boot:
#   - lambda: |-
#       id(overtheair).set_auth_password(to_string("${new_ota_pwd}"));

# Enable logging
logger:
  level: WARN

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - ep_esphome_device_shelly_plus1pm.yaml # Device-specific defaults
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s
