# Device: Sonoff NSPanel with HomeAssistant & Blackymas NSPanel_HA_Blueprint
# Note to self:
# - dallas - mod: no
# - installerad i bastukammaren
# - relay2 styr värme-element 
# - relay1 styr lampor
# - button2 styr lampor/relay1
# - inga dallas modifikationer

# Blackymas templates:
# core : https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_esphome_core.yaml
# tft_upload : https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_esphome_addon_upload_tft.yaml

substitutions:

###### CHANGE ME START ######
## generic env settings
  network: "192.168.12"
  device_num: "67"
  device_type: "sonoff-nspanel"
  device_subtype: ""
  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "nspanel i bastukammaren utan dallas-sensorer"
  em_route: ""

## nspanel & blackymas related
  # baud_rate: "921600" # note: this has to match with the baudrate set in the currently running TFT
  #baud_rate: "115200"
  #nextion_update_url: "http://esphome.edupihi.home/download.bin?configuration=dummy-nspanel-tft.yaml&file=nspanel_eu.tft&download=nspanel_eu.tft" # URL to local tft File
  nextion_update_url: "http://192.168.12.3:8123/local/nspanel/nspanel_eu.tft"
#### CHANGE ME END #####

#### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
     # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
     # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
     # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s
  remote_package_two:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - "devices/ep_esphome_device_sonoff_nspanel_blackymas_override.yaml"
    refresh: 300s

#### My customization - Start #####

logger:
  level: WARN

switch:
  - id: !extend relay_1
    pin: GPIO20 # remove pin 22 usage, gpio20 is unconnected

output:
  - platform: gpio
    id: output_1
    pin: GPIO22
  # x75-eh-sonoff-dualr3pow = har gruppen 'x75-eh-sonoff-dualr3pow/light/light_group_utelampor'
  - platform: template
    type: binary
    id: _virtual_light_output_1
    write_action:
      - mqtt.publish:
          topic: "x75-eh-sonoff-dualr3pow/light/light_group_utelampor/command"
          payload: '{"state": "TOGGLE"}'

light:
  - platform: binary
    name: "Light 1"
    id: light_1
    output: output_1
  - platform: binary
    name: "x${device_num} Virtual light 1"
    id: _virtual_light_1
    #internal: True
    output: _virtual_light_output_1

climate:
  - platform: thermostat
    name: "Thermostat Climate Controller 01"
    visual:
      min_temperature: 6
      max_temperature: 25
      temperature_step: 0.5
    sensor: temp_nspanel
    min_heating_off_time: 0s
    min_heating_run_time: 0s
    min_idle_time: 0s
    heat_deadband: 0.5 # turn on heating when 0.5 under set_temp 
    heat_overrun: 0.0 # no need, temp will overrun by 0.2-0.3 anyway
    heat_action:
      - switch.turn_on: relay_2
    idle_action:
      - switch.turn_off: relay_2
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 12 °C

binary_sensor:
  ###### OVERRIDE THE BEHAVIOUR SPECIFIED IN BLACKYMAS TEMPLATE #####
  ###### LEFT BUTTON BELOW DISPLAY "HARDWIRED" TO DO NOTHING#####
  - id: !extend left_button
    on_multi_click:
      - timing:
          - ON for at most 0.8s
        then:
          - logger.log: "Left button - Short click"
          #- switch.toggle: relay_1
  ###### OVERRIDE THE BEHAVIOUR SPECIFIED IN BLACKYMAS TEMPLATE #####
  ###### RIGHT BUTTON BELOW DISPLAY "HARDWIRED" TO TOGGLE RELAY_1#####
  - id: !extend right_button
    on_multi_click:
      - timing:
          - ON for at most 0.8s
        then:
          - logger.log: "Right button - Short click"
          - light.toggle: light_1
