# Device: Sonoff NSPanel with HomeAssistant & Blackymas NSPanel_HA_Blueprint
# Note to self:
# - dallas - mod: yes
# - installerad i kojerasia i vinterträdegården
# - dallas sensor adress 0xc800000de537b428 går till vinterträdgårdens golvtermometer-kanal
# - dallas sensor adress 0x2fdda62912646128 är dragen till sovrummert golvtermometer-kanal
# - relay1 är okopplat
# - relay2 är okopplat
# - template-switch 1 skickar HeatON/OFF meddelande över mqtt till eh_sonoff_4chpror3_x01 / heat_control_1
# - template-switch 2 skickar HeatON/OFF meddelande över mqtt till eh_sonoff_4chpror3_x01 / heat_control_2  

# Blackymas templates:
# core : https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_esphome_core.yaml
# tft_upload : https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_esphome_addon_upload_tft.yaml

substitutions:

###### CHANGE ME START ######
## generic env settings
  network: "192.168.12"
  device_num: "71"
  device_type: "sonoff-nspanel"
  device_subtype: ""
  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "nspanel i wiga med 2 st golvtemp-sensorer, 1 = wiga, 2 = sovrum"
  em_route: ""

## nspanel & blackymas related
  # baud_rate: "921600" # note: this has to match with the baudrate set in the currently running TFT
  #baud_rate: "115200"
  #nextion_update_url: "http://esphome.edupihi.home/download.bin?configuration=dummy-nspanel-tft.yaml&file=nspanel_eu.tft&download=nspanel_eu.tft" # URL to local tft File
  nextion_update_url: "http://192.168.12.3:8123/local/nspanel/nspanel_eu.tft"
#### CHANGE ME END #####

#### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
     # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
     # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
     # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s
  remote_package_two:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - "devices/ep_esphome_device_sonoff_nspanel_blackymas_override.yaml"
    refresh: 300s

#### My customization - Start #####

# wifi:
#   networks:
#     - id: !extend wifi_default
#       manual_ip:
#         # Set this to the IP of the ESP (in network 192.168.12.64/26 = range: 192.168.12.65 - 192.168.12.126)
#         static_ip: ${device_ip}
#         gateway: "${network}.1"
#         subnet: 255.255.255.0
#         dns1: "${network}.2" # Local PiHole 
#         dns2: 94.140.14.14 # AdGuard DNS Primary

# web_server:
#   port: 80
#   auth:
#     username: admin
#     password: ${wifi_password}

logger:
  level: WARN

dallas:
  - pin: 23

## Provide a virtual light-group switch
output:
  # x75-eh-sonoff-dualr3pow = har gruppen 'x75-eh-sonoff-dualr3pow/light/light_group_utelampor'
  - platform: template
    type: binary
    id: _virtual_light_output_1
    write_action:
      - mqtt.publish:
          topic: "x75-eh-sonoff-dualr3pow/light/light_group_utelampor/command"
          payload: '{"state": "TOGGLE"}'

light:
  - platform: binary
    name: "x${device_num} Virtual light 1"
    id: _virtual_light_1
    #internal: True
    output: _virtual_light_output_1

sensor:
  # Dallas/One-wire bus
  - platform: dallas
    address: 0xc800000de537b428
#    index: 0
    name: "Floor Temperature 1"
    id: floor_temperature_01
  - platform: dallas
    address: 0x2fdda62912646128
#    index: 1
    name: "Floor Temperature 2"
    id: floor_temperature_02

switch:
  - platform: template
    name: "Heating Control 1"
    id: heating_control_1
    turn_on_action:
      - then:
        - mqtt.publish:
           topic: "eh_sonoff_4chpror3_x01/switch/eh_sonoff_4chpror3_x01_heat_control_1/command"
           payload: "ON"
        - switch.template.publish:
            id: heating_control_1
            state: ON
    turn_off_action:
      - then:
        - mqtt.publish:
           topic: "eh_sonoff_4chpror3_x01/switch/eh_sonoff_4chpror3_x01_heat_control_1/command"
           payload: "OFF"
        - switch.template.publish:
            id: heating_control_1
            state: OFF
  - platform: template
    name: "Heating Control 2"
    id: heating_control_2
    turn_on_action:
      - then:
        - mqtt.publish:
           topic: "eh_sonoff_4chpror3_x01/switch/eh_sonoff_4chpror3_x01_heat_control_2/command"
           payload: "ON"
        - switch.template.publish:
            id: heating_control_2
            state: ON
    turn_off_action:
      - then:
        - mqtt.publish:
           topic: "eh_sonoff_4chpror3_x01/switch/eh_sonoff_4chpror3_x01_heat_control_2/command"
           payload: "OFF"
        - switch.template.publish:
            id: heating_control_2
            state: OFF

text_sensor:
  - platform: template
    name: Dallas Address 1
    lambda: |-
      return id(floor_temperature_01).get_address_name();
  - platform: template
    name: Dallas Address 2
    lambda: |-
      return id(floor_temperature_02).get_address_name();

climate:
  - platform: thermostat
    name: "Thermostat Climate Controller 01"
    visual:
      min_temperature: 10
      max_temperature: 25
      temperature_step: 0.5
    sensor: floor_temperature_01
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 180s
    heat_deadband: 0.5 # turn on heating when 0.5 under set_temp 
    heat_overrun: 0.0 # no need, temp will overrun by 0.2-0.3 anyway
    heat_action:
      #- switch.turn_on: relay_1
      - switch.turn_on: heating_control_1
    idle_action:
      #- switch.turn_off: relay_1
      - switch.turn_off: heating_control_1
    off_mode:
      - switch.turn_off: heating_control_1
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 12 °C
  - platform: thermostat
    name: "Thermostat Climate Controller 02"
    visual:
      min_temperature: 10
      max_temperature: 25
      temperature_step: 0.5
    sensor: floor_temperature_02
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 180s
    heat_deadband: 0.5 # turn on heating when 0.5 under set_temp 
    heat_overrun: 0.0 # no need, temp will overrun by 0.2-0.3 anyway
    heat_action:
      #- switch.turn_on: relay_2
      - switch.turn_on: heating_control_2
    idle_action:
      #- switch.turn_off: relay_2
      - switch.turn_off: heating_control_2
    off_mode:
      - switch.turn_off: heating_control_2
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 18 °C

#### My customization - End #####
