# Device: Sonoff DualR3-POW V1.6 20200910 with CSE7761 power chip 
substitutions:
  network: "192.168.12"
  device_num: "82"
  device_type: "sonoff-dualr3pow"
  device_subtype: "v1.6"

  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "Jule arbetsrum, i kopplingsskåp, "
  em_route: ""
  em_update_interval: 5s

# Enable logging
logger:
  level: WARN

switch:
  - id: !extend switch_1
    restore_mode: ALWAYS_ON

# styrning av krets 2 på sw2
binary_sensor:
  - id: !extend switch_sensor_2
    # override default toggling when switched, now SWITCH_ON = RELAY_ON IF OFF, SWITCH_OFF = RELAY_OFF IF ON
    on_state: 
      then: 
        - lambda: |-
            if (id(switch_sensor_2).state) {
              // Binary sensor is ON, do something here
              id(switch_2).turn_on();
            } else {
              // Binary sensor is OFF, do something else here
              id(switch_2).turn_off();
            }

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - devices/ep_esphome_device_sonoff_dualr3pow_v1.yaml # Device-specific defaults
    refresh: 300s
