# Device: Sonoff Mini V2.0 2021.04.27 (YX-01 94V-0 E302201) 
substitutions:
  network: "192.168.12"
  device_num: "83"
  device_type: "panasonic-z25ufeaw"
  device_subtype: ""
  
  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  # admin_password: !secret otaPWD
  # new_ota_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "Lufvärmpump i vardagsrum"
  em_route: "l|?"

# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
esphome:
  name: ${device_name}
#  on_boot:
#    - lambda: |-
#        id(overtheair).set_auth_password(to_string("${new_ota_password}"));

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: WARN

#wifi:
#   use_address: 192.168.12.222

uart:
  tx_pin: GPIO33
  rx_pin: GPIO34
  baud_rate: 9600
  parity: EVEN

sensor:
  - platform: template
    name: Temperature
    update_interval: 60s
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    lambda: |-
      return id(pana).current_temperature;

climate:
  - platform: panasonic_ac
    # For CZ-TACG1
    id: pana
    type: cnt
    name: Climate PanasonicAC 01
    visual:
      min_temperature: 8
      max_temperature: 25
      temperature_step: 0.1
#    horizontal_swing_select:
#      name: Panasonic AC Horizontal Swing Mode
    vertical_swing_select:
      name: AC Vertical Swing Mode
    outside_temperature:
      name: AC Outside Temperature

    # Enable as needed
    # eco_switch:
    #   name: Panasonic AC Eco Switch
    # econavi_switch:
    #   name: Panasonic AC Econavi Switch
    nanoex_switch:
      name: AC NanoeX Switch
    # mild_dry_switch:
    #   name: Panasonic AC Mild Dry Switch
    current_power_consumption:
      name: AC Power Consumption

    # Useful when the ac does not report a current temperature (CZ-TACG1 only)
    # current_temperature_sensor: temperature_sensor_id

external_components:
  source: github://DomiStyle/esphome-panasonic-ac
  components: [panasonic_ac]

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
    refresh: 300s

