# Device: Sonoff DualR3-POW V2.0 20210427 with BL0930 power chip 

# Notes to self:
# Installerad i taket i sovrummet (2. taklampans jakorasia)
# 1.taklampans trapp-brytare dragen till S1
# 2.taklampans brytare dragen till S2
# 1. taklampa p책 relay 1 (smart lampa + fl채kt, delayed always-on, S1 'on_state' skickar MQTT-Toggle)
# 2. taklampa p책 relay 2 (on/off lampa)
# NOTTODO: dra Tuya-seriekabel fr책n lampa hit o skippa MQTT-Toggle

substitutions:
  network: "192.168.12"
  device_num: "90"
  device_type: "sonoff-dualr3pow"
  device_subtype: "v2.0"

  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  # admin_password: !secret otaPWD
  # new_ota_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "Sovrummets taklampor, S2 mqtt toggle till mantratuya, R2 (delayed always on) powers mantratuya, S1 & R1 normal light conf"
  em_route: ""
  em_update_interval: 5s

# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
esphome:
  on_boot:
    #- lambda: |-
    #    id(overtheair).set_auth_password(to_string("${new_ota_password}"));
    - switch.turn_off: switch_1
    - delay: 60s
    - switch.turn_on: switch_1

#wifi:
#  use_address: 192.168.12.214

# Enable logging
logger:
  level: WARN

# add light-entity for relays that steer lights
light:
  - platform: binary
    name: "Light 2"
    output: output_2
    id: light_2

switch:
  # hide switch that's configured as a light
  - id: !extend switch_2
    internal: True

binary_sensor:
  - id: !extend switch_sensor_1
    on_state:
      - logger.log: "$device_name Switch Sensor 1 State Changed"
      - mqtt.publish:
          topic: "x91-eh-mantra-tuya/light/dimmable_light/command"
          payload: '{"state":"TOGGLE"}'
  - id: !extend switch_sensor_2
    on_state:
      - light.toggle: light_2

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - devices/ep_esphome_device_sonoff_dualr3pow_v2.yaml # Device-specific defaults
    refresh: 300s

