# Device: Sonoff DualR3-POW V1.6 20200910 with CSE7761 power chip 
substitutions:
  network: "192.168.12"
  device_num: "92"
  device_type: "shelly-plus2pm"
  device_subtype: "v0.1.9"
  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  # admin_password: !secret admin_password
  admin_password: !secret otaPWD
  new_ota_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "WiGa lampor, kojerasia vid dubbeldörr"
  em_route: ""
  em_update_interval: 5s

# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
esphome:
 on_boot:
   - lambda: |-
       id(overtheair).set_auth_password(to_string("${new_ota_password}"));

wifi:
  use_addreass: 192.168.12.157

# Enable logging
logger:
  level: WARN
  #level: DEBUG
  logs:
    mqtt.component: WARN
    mqtt.client: ERROR
    sensor: WARN
    text_sensor: WARN
    esp32.preferences: WARN
    #ep_cse7761: DEBUG

# add light-entities for relays that steer lights
light:
  - platform: binary
    name: "Light 1"
    output: output_1
    id: light_1
  - platform: binary
    name: "Light 2"
    output: output_2
    id: light_2
# hide/make internal the switches since we're controlling the relays via 'light'
switch:
  - id: !extend switch_1
    internal: True
  - id: !extend switch_2
    internal: True

binary_sensor:
  - id: !extend switch_sensor_1
    on_state: 
      - logger.log: "Switch 1 state changed - Toggling light 1" 
      - light.toggle: light_1
  - id: !extend switch_sensor_2
    on_state: 
      - logger.log: "Switch 2 state changed - Not configured" 
      - light.toggle: light_2

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - devices/ep_esphome_device_shelly_plus2pm_v0.1.9.yaml # Device-specific defaults
    refresh: 300s
