# Notes to self:
# Installerad i väggen vid köksdörren (översta kojerasian med peitelevy)
# Hallens taklampa trapp-brytare dragen till S1
# Vardagsrummets taklampa trapp-brytare dragen till S2
# Alla brytare är vipp-brytare.
# Hallens taklampa på relay 1 (on/off lampa)
# Vardagsrummets taklampa på relay 2 (on/off lampa)

substitutions:
  network: "192.168.12"
  device_num: "94"
  device_type: "sonoff-dualr3lite"
  device_subtype: ""

  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  # admin_password: !secret otaPWD
  # new_ota_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "Vardagsrum, lampor, R1: hallen, R2: vardagsrum"
  em_route: ""

# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
# esphome:
#   on_boot:
#     - lambda: |-
#         id(overtheair).set_auth_password(to_string("${new_ota_password}"));
# wifi:
#   use_address: 192.168.12.205

logger:
  level: WARN

binary_sensor:
  - id: !extend switch_sensor_1
    on_state: !remove
    on_press:
      - logger.log: "Switch Sensor 1 state PRESSED - toggling relay 1"
      - light.toggle: light_1
  - id: !extend switch_sensor_2
    on_state: !remove
    on_press:
      - logger.log: "Switch Sensor 2 state PRESSED - toggling relay 2"
      - light.toggle: light_2

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - devices/ep_esphome_device_sonoff_dualr3lite_v2.yaml
    refresh: 300s

