# Notes to self:

substitutions:
  network: "192.168.12"
  device_num: "95"
  device_type: "sonoff-dualr3lite"
  device_subtype: ""

  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "Lilla badrum, lampor, R1: tak, R2: spegel"
  em_route: ""

logger:
  level: WARN

binary_sensor:
  - id: !extend switch_sensor_1
    on_state:
      - logger.log: "Switch Sensor 1 state change - toggling relay 1"
      - light.toggle: light_1
  - id: !extend switch_sensor_2
    on_state:
      - logger.log: "Switch Sensor 2 state change - toggling relay 2"
      - light.toggle: light_2

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - devices/ep_esphome_device_sonoff_dualr3lite_v2.yaml
    refresh: 300s

