# Set variables such as the device's name and friendly name
# The devicename is used internally which the friendly name is shown in the user interface
# Device: Shelly Plus 1PM 
substitutions:
  network: "192.168.12"
  device_num: "97"
  device_type: "shelly-plus1pm"
  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  # admin_password: !secret otaPWD
  # new_ota_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_update_interval: 5s
  em_usage: "Vägglampa vardagsrum"
  em_route: ""

# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
# esphome:
#   on_boot:
#     - lambda: |-
#         id(overtheair).set_auth_password(to_string("${new_ota_password}"));
# wifi:
#   use_address: 192.168.12.246

# Enable logging
logger:
  level: WARN

# add light-entity for relays that steer lights
light:
  - platform: binary
    name: "Light 1"
    output: output_1
    id: light_1

switch:
  # hide switch
  - id: !extend switch_1
    internal: True

binary_sensor:
  - id: !extend switch_sensor_1
    on_state: 
      light.toggle: light_1

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - devices/ep_esphome_device_shelly_plus1pm.yaml # Device-specific defaults
    refresh: 300s
