# Set variables such as the device's name and friendly name
# The devicename is used internally which the friendly name is shown in the user interface
# Device: Shelly Plus 1PM 
substitutions:
  network: "192.168.12"
  device_num: "98"
  device_type: "shelly-1l"

  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  #admin_password: !secret otaPWD
  #new_ota_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "Golvlampa"
  em_route: ""

# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
#esphome:
# on_boot:
#   - lambda: |-
#       id(overtheair).set_auth_password(to_string("${new_ota_password}"));

#wifi:
#  use_address: 192.168.12.243

# Enable logging
logger:
  level: WARN

mqtt:
  # override default tls connection, since esp8266 mqtt-component is broken 
  broker: mqtt.edupihi.home
  port: 1883
  # remove the esp-idf specific mqtt settings from core.yaml
  skip_cert_cn_check: !remove
  idf_send_async: !remove
  certificate_authority: !remove

binary_sensor:
#  - id: !extend switch_sensor_1
#    on_state:
#      - logger.log: "$device_name Toggle Light 1 on Switch 1"
#      - light.toggle: light_1
#    filters:
#      - delayed_on_off: 50ms
  - id: !extend switch_sensor_2
    on_state:
      - logger.log: "$device_name Toggle Light 1 on Switch 2"
      - light.toggle: light_1
    filters:
      - delayed_on_off: 50ms

packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - devices/ep_esphome_device_shelly_1l.yaml
    refresh: 300s


  


