# Device: Sonoff Mini V2.0 2021.04.27 (YX-01 94V-0 E302201) 
substitutions:
  network: "192.168.12"
  device_num: "99"
  device_type: "sonoff-minir2"
  device_subtype: ""

  device_name: x${device_num}-eh-${device_type}
  device_ip: "${network}.${device_num}"
  admin_password: !secret admin_password
  # admin_password: !secret otaPWD
  # new_ota_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_password
  mqtt_broker: !secret mqtt_broker
  ca_certificates: !secret letsencrypt_cacerts

## ep energy mgmt
  em_usage: "Baljans vattentemp. sensorer, relä oanvänt"
  em_route: ""

# to change the ota-password, update once with old pw and uncomment this on_boot to set a new pw
# esphome:
#   on_boot:
#     - lambda: |-
#         id(overtheair).set_auth_password(to_string("${new_ota_password}"));

# wifi:
#   use_address: 192.168.12.223

logger:
  level: WARN

mqtt:
  # override default tls connection, since esp8266 mqtt-component is broken 
  broker: mqtt.edupihi.home
  port: 1883
  # remove the esp-idf specific mqtt settings from core.yaml
  skip_cert_cn_check: !remove
  idf_send_async: !remove
  certificate_authority: !remove

# binary_sensor:
#   - id: !extend switch_sensor_1
#     on_state:
#       - logger.log: "Toggle Light 1"
#       - light.toggle: "light_1"

light:
  - id: !remove light_1

binary_sensor:
  - id: !remove switch_sensor_1
  
dallas:
  - pin: GPIO03
    update_interval: 5s

sensor:
  # Dallas/One-wire bus
  - platform: dallas
    address: 0xda00000ce23c1a28
#    index: 0
    name: "Temperature 1"
    id: temperature_01
  - platform: dallas
    address: 0x9b00000ce21fed28
#    index: 1
    name: "Temperature 2"
    id: temperature_02

text_sensor:
  - platform: template
    name: Dallas Address 1
    lambda: |-
      return id(temperature_01).get_address_name();
  - platform: template
    name: Dallas Address 2
    lambda: |-
      return id(temperature_02).get_address_name();


packages:
  remote_package:
    url: https://github.com/pihiandreas/esphome_components
    ref: main
    files:
      - ep_esphome_core.yaml # Core package
      - devices/ep_esphome_device_sonoff_minir2.yaml
    refresh: 300s
