# Device: Shelly 3EM
# MCU: ESP8266EX / 160MHz? / 4M
# EM: ADE7880

# substitutions:
#   # Higher value gives lower watt readout
#   current_res: "0.001"
#   # Lower value gives lower voltage readout
#   voltage_div: "1925"
#   update_interval: ${em_update_interval}

external_components:
  - source:
      type: git
      url: https://github.com/pihiandreas/esphome_components
      ref: main
    components: [ ep_em_ade7880 ]

esphome:
  name: $device_name

esp8266:
  # board: esp01_1m
  board: espduino # use espduino (4MB) instead of generic 8266 (1M)

i2c:
  sda: GPIO12
  scl: GPIO14
  frequency: 200kHz

output:
  - platform: gpio
    id: output_1
    pin:
      number: GPIO15

switch:
  - platform: output
    id: switch_1
    name: "Switch 1"
    output: "output_1"
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: "Button 1"
    id: button_sensor_1
    on_state:
      - logger.log: 
          format: "Button 1 state changed - No action configured"
          level: WARN
    # filters:
    #   - delayed_on_off: 50ms

sensor:
  - platform: ep_em_ade7880
    id: ade7880_device
    irq0_pin:
      number: GPIO13
    irq1_pin:
      number: GPIO5
    reset_pin:
      number: GPIO16
    frequency: 50Hz
    update_interval: ${em_update_interval}
    phase_a:
      name: L1
      voltage: Voltage
      current: Current
      active_power: Active Power
      power_factor: Power Factor
      forward_active_energy: Energy
      reverse_active_energy: Reverse Energy
      calibration:
        current: 3116628
        voltage: -757178
        power: -1344457
        phase_angle: 188
    phase_b:
      name: L2
      voltage: Voltage
      current: Current
      active_power: Active Power
      power_factor: Power Factor
      forward_active_energy: Energy
      reverse_active_energy: Reverse Energy
      calibration:
        current: 3133655
        voltage: -755235
        power: -1345638
        phase_angle: 188
    phase_c:
      name: L3
      voltage: Voltage
      current: Current
      active_power: Active Power
      power_factor: Power Factor
      forward_active_energy: Energy
      reverse_active_energy: Reverse Energy
      calibration:
        current: 3111158
        voltage: -743813
        power: -1351437
        phase_angle: 180
    neutral:
      name: N
      current: Current
      calibration:
        current: 311123

status_led:
  pin: GPIO2
